#
# Copyright (c) Haulmont 2024. All Rights Reserved.
# Use is subject to license terms.
#

# This is a lightweight configuration with Flowset control application + database that does not include Camunda 7.
# See docker-compose-full.yml for a full configuration that includes external Camunda 7.

services:
  flowset-control-app: # Flowset Сontrol web application exposed on the configured port (by default 8081)
    image: flowset/flowset-control:latest
    container_name: flowset-control-app
    build: ..
    restart: "no"
    environment:
      MAIN_DATASOURCE_URL: "jdbc:postgresql://flowset-control-database/${FLOWSET_CONTROL_DB_NAME}"
      MAIN_DATASOURCE_USERNAME: "${FLOWSET_CONTROL_DB_USERNAME}"
      MAIN_DATASOURCE_PASSWORD: "${FLOWSET_CONTROL_DB_PASSWORD}"
      SERVER_PORT: "${FLOWSET_CONTROL_SERVER_PORT}"
      UI_LOGIN_DEFAULTUSERNAME: "${FLOWSET_CONTROL_UI_DEFAULT_USERNAME}"
      UI_LOGIN_DEFAULTPASSWORD: "${FLOWSET_CONTROL_UI_DEFAULT_PASSWORD}"
    ports:
      - "${FLOWSET_CONTROL_SERVER_PORT}:${FLOWSET_CONTROL_SERVER_PORT}"
    depends_on:
      flowset-control-database:
        condition: service_started
    healthcheck:
      test: curl --fail --silent http://localhost:$$SERVER_PORT/actuator/health | grep UP || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  flowset-control-database: # PostgresQL database used by Flowset Сontrol web application
    image: postgres:16.3
    container_name: flowset-control-database
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - flowset-control-database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${FLOWSET_CONTROL_DB_USERNAME}"
      POSTGRES_PASSWORD: "${FLOWSET_CONTROL_DB_PASSWORD}"
      POSTGRES_DB: "${FLOWSET_CONTROL_DB_NAME}"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  flowset-control-database_data: